### ISSUE TITLE
Request Deprecation Question

### ISSUE THREAD

**Issue by justwlocke** [lino-levan/better-node-gtts#2]
Hello!

I found this module while looking for some text-to-speech modules, and I like how this can generate wav files.

I was wondering though, [with Request being deprecated](https://github.com/request/request/issues/3142), did you have any plans to remove/replace it with something that is still being supported?

**Comment by lino-levan** [comment]
Ah, I did not know that request was being deprecated. Let me see if I can try to replace it really quickly. Thanks for the issue!

**Comment by lino-levan** [comment]
Closed by https://github.com/lino-levan/better-node-gtts/commit/e9833f016866e624f3bca675c6adaf72dbb89326!
