### ISSUE TITLE
how do you put it in another language?

### ISSUE THREAD

**Issue by edergames29** [lino-levan/better-node-gtts#4]
how do you put it in another language?

**Comment by edergames29** [comment]
var gTTS = require("better-node-gtts")("pt") dont work

**Comment by lino-levan** [comment]
What language are you trying to use?

**Comment by edergames29** [comment]
> Que idioma você está tentando usar?

Brazilian Portuguese and Portuguese Portuguese

**Comment by lino-levan** [comment]
Have you tried the `Text2Speech` class?

I don't write a lot of node anymore but something like:
```ts
const { Text2Speech } = require("better-node-gtts")
const pt = new Text2Speech("pt");
```

**Comment by fukemy** [comment]
Hi do you support other people speech voice? It's only default once speech voice

**Comment by lino-levan** [comment]
We only support the default google voice, sorry.
